"""
Konversi satellite_texture.jpg ke satellite_bundle.js
untuk diload langsung di browser tanpa CORS error.
"""
import base64, os, json

INPUT_JPG = r"D:\ITB2\Pak_RK\MetOcean_Tulungagung\kode_zahy\WindModel3DProject\visualization\satellite_texture.jpg"
OUTPUT_JS  = r"D:\ITB2\Pak_RK\MetOcean_Tulungagung\kode_zahy\WindModel3DProject\visualization\satellite_bundle.js"
META_JSON  = INPUT_JPG.replace('.jpg', '_meta.json')

with open(INPUT_JPG, 'rb') as f:
    b64 = base64.b64encode(f.read()).decode('utf-8')

meta = {}
if os.path.exists(META_JSON):
    with open(META_JSON) as f:
        meta = json.load(f)

js_content = f"""// Auto-generated by make_satellite_bundle.py
// Satelit Tulungagung | Bbox: {meta.get('bbox', {})}
// Zoom: {meta.get('zoom', '?')} | Size: {meta.get('output_size', '?')}
window.SATELLITE_TEXTURE_BASE64 = 'data:image/jpeg;base64,{b64}';
console.log('[Satelit] Tekstur ter-bundle:', window.SATELLITE_TEXTURE_BASE64.length, 'chars');
"""

with open(OUTPUT_JS, 'w') as f:
    f.write(js_content)

size_kb = os.path.getsize(OUTPUT_JS) / 1024
print(f"Saved: {OUTPUT_JS} ({size_kb:.0f} KB)")
