"""
process_sentinel2.py — Analisis & Konversi Sentinel-2 GeoTIFF ke Bundle JS
=============================================================================
1. Membaca sentinel2_texture_wgs84.tif (1.2 GB) menggunakan rasterio/PIL.
2. Menganalisis metadata, resolusi, band RGB, dan bounding box.
3. Melakukan resampling ke 2048x2048 dengan contrast stretch (uint8).
4. Menyimpan sebagai visualization/sentinel2_texture.jpg.
5. Membungkus ke visualization/sentinel2_bundle.js (window.SENTINEL2_TEXTURE_BASE64).
"""

import os, sys, base64
import numpy as np
import rasterio
from rasterio.enums import Resampling
from PIL import Image

# Mencegah error DecompressionBomb untuk gambar besar di PIL
Image.MAX_IMAGE_PIXELS = None

ROOT = r"D:\ITB2\Pak_RK\MetOcean_Tulungagung\kode_zahy\WindModel3DProject"
INPUT_TIF = os.path.join(ROOT, "Data", "Texture", "sentinel2_texture_wgs84.tif")
OUTPUT_JPG = os.path.join(ROOT, "visualization", "sentinel2_texture.jpg")
OUTPUT_JS  = os.path.join(ROOT, "visualization", "sentinel2_bundle.js")

def analyze_and_convert():
    print("=" * 60)
    print("  Sentinel-2 Texture Analyzer & Bundler")
    print("=" * 60)
    if not os.path.exists(INPUT_TIF):
        print(f"[ERROR] File tidak ditemukan: {INPUT_TIF}")
        return

    file_size_mb = os.path.getsize(INPUT_TIF) / (1024 * 1024)
    print(f"[INFO] File TIF: {INPUT_TIF} ({file_size_mb:.1f} MB)")

    with rasterio.open(INPUT_TIF) as src:
        print(f"[INFO] Dimensions : {src.width} x {src.height}")
        print(f"[INFO] Bands      : {src.count}")
        print(f"[INFO] CRS        : {src.crs}")
        print(f"[INFO] Bounds     : {src.bounds}")
        print(f"[INFO] Dtype      : {src.dtypes}")

        # Tentukan target ukuran (2048x2048 agar ringan di WebGL & browser)
        target_size = (2048, 2048)
        print(f"[INFO] Resampling ke {target_size} (Bilinear)...")

        # Baca 3 band pertama sebagai RGB
        bands_to_read = min(3, src.count)
        data = src.read(
            out_shape=(bands_to_read, target_size[1], target_size[0]),
            resampling=Resampling.bilinear
        )

    # Normalize ke uint8
    rgb = np.zeros((target_size[1], target_size[0], 3), dtype=np.uint8)
    for i in range(3):
        if i < bands_to_read:
            band = data[i]
            b_min, b_max = np.nanmin(band), np.nanmax(band)
            print(f"  Band {i+1} min: {b_min}, max: {b_max}")
            
            # Percentile stretch untuk kontras optimal
            p2, p98 = np.percentile(band[~np.isnan(band)], (1, 99))
            if p98 > p2:
                stretched = np.clip((band - p2) / (p98 - p2) * 255.0, 0, 255)
            else:
                stretched = np.clip((band - b_min) / (b_max - b_min + 1e-5) * 255.0, 0, 255)
            rgb[:, :, i] = stretched.astype(np.uint8)
        else:
            rgb[:, :, i] = 0

    print(f"[INFO] Menyimpan gambar ke {OUTPUT_JPG}...")
    img = Image.fromarray(rgb, 'RGB')
    img.save(OUTPUT_JPG, 'JPEG', quality=88)

    print(f"[INFO] Mengencode ke Base64 bundle {OUTPUT_JS}...")
    with open(OUTPUT_JPG, 'rb') as f:
        b64 = base64.b64encode(f.read()).decode('utf-8')

    js_content = f"""// Auto-generated by process_sentinel2.py
// Sentinel-2 Imagery Tulungagung & Trenggalek (WGS84)
// Original size: {file_size_mb:.1f} MB | Resampled: 2048x2048
window.SENTINEL2_TEXTURE_BASE64 = 'data:image/jpeg;base64,{b64}';
console.log('[Sentinel-2] Tekstur ter-bundle:', window.SENTINEL2_TEXTURE_BASE64.length, 'chars');
"""
    with open(OUTPUT_JS, 'w', encoding='utf-8') as f:
        f.write(js_content)

    js_size_mb = os.path.getsize(OUTPUT_JS) / (1024 * 1024)
    print(f"[SUCCESS] Tersimpan: {OUTPUT_JS} ({js_size_mb:.2f} MB)")
    print("[DONE] Analisis dan pemrosesan Sentinel-2 selesai!")

if __name__ == "__main__":
    analyze_and_convert()
